# Generated by Django 5.2.2 on 2025-06-11 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassenrollment',
            old_name='class_instance',
            new_name='enrolled_class',
        ),
        migrations.RemoveField(
            model_name='studentclassenrollment',
            name='enrolled_on',
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='roll_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
