# Generated by Django 5.2.2 on 2025-06-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_rename_class_instance_studentclassenrollment_enrolled_class_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclassenrollment',
            unique_together={('enrolled_class', 'roll_number')},
        ),
    ]
