# Generated by Django 5.2.2 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_user_approval_status_user_feedback_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclassenrollment',
            unique_together={('enrolled_class', 'student')},
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='studentclassenrollment',
            name='roll_number',
        ),
    ]
