# Generated by Django 5.2.2 on 2025-06-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0008_alter_studentclassenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='attendance_reports/'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('processing', 'Processing'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
